apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
spec:
  replicas: 1  # Adjust the number of replicas based on your requirements
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
        - name: wisecow-container
          image: akshaya12/wisecow:1.0  # Replace with your actual Docker image
          ports:
            - containerPort: 3000  # Adjust based on your application's port

