apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  selector:
    app: wisecow
  ports:
    - protocol: TCP
      port: 80  # Adjust based on your service's port
      targetPort: 3000  # Adjust based on your application's port
  type: LoadBalancer  # Change to NodePort or ClusterIP based on your needs

